edit views
mikiya1130/Amazon pull request #9
Opened 2021-07-03 10:09 UTC by mhrwh

おねがいします

2021-07-04 11:35 UTC, mikiya1130 reviewed
base64からの変換は書いてくれた感じでOKだと思います。
`try-except-else-finally`もその通りです。
あとは計算処理よろしくお願いします。

2021-07-04 11:35 UTC, mikiya1130 commented on measurevolume/views.py
> +import json
`import json`不要なら削除、これから使うならそのままで大丈夫です。

2021-07-04 11:35 UTC, mikiya1130 commented on measurevolume/views.py
> +        mm_pixel = get_chopsticks_length_per_pixel()
それぞれの第1引数に画像データ(変数`src`)を指定してください。

2021-07-04 11:35 UTC, mikiya1130 commented on measurevolume/views.py
> +
else句の中で`exist_glass`と`exist_chopsticks`に`True`を代入してください。

2021-07-06 02:38 UTC, mhrwh commented
計算処理以外修正しました。

finallyいらない？
exist_glassとexist_chopsticksについて相談したいことがある。
会ったときにお願いします。

2021-07-06 07:19 UTC, mhrwh commented
計算処理追加しました。一応テストもしました。

スライスで3行ごと取り出して１の数を数えて平均の半径を求めた。
np.count_nonzero(img, axis=1)で１行ごとの１の数が配列で得られる。
どっちがいいかな？

detect_water_areaでもらうnumpy配列のことで確認したいことがある。
あったときに

2021-07-06 07:20 UTC, mhrwh commented
変数後で変えます。

2021-07-06 14:32 UTC, mikiya1130 requested changes
修正ありがとうございます。
`finally`に関しては、動作としては変わらないはずなので、どちらでも大丈夫です。

見逃してたけど、エラーが出るともう一方の`exist_###`が未定義になりそうです。

#### NotFoundGlassErrorの場合
```Python
try:
    img = detect_water_area(src)  # -> throw NotFoundGlassError
    mm_pixel = get_chopsticks_length_per_pixel(src)
except NotFoundGlassError:
    exist_glass = False
    volume = -1
except NotFoundChopsticksError:
    # 実行されない
else:
    # 実行されない
finally:
    data = {
        "exist_glass": exist_glass,  # Flase
        "exist_chopsticks": exist_chopsticks,  # 未定義
        "volume": volume,  # -1
    }
```

#### NotFoundChopsticksErrorの場合
```Python
try:
    img = detect_water_area(src)
    mm_pixel = get_chopsticks_length_per_pixel(src)  # -> throw NotFoundChopsticksError
except NotFoundGlassError:
    # 実行されない
except NotFoundChopsticksError:
    exist_chopsticks = False
    volume = -1
else:
    # 実行されない
finally:
    data = {
        "exist_glass": exist_glass,  # 未定義
        "exist_chopsticks": exist_chopsticks,  # False
        "volume": volume,  # -1
    }
```

例えばこんな感じで初期化してから`try`入ったほうがいいかも
```Python
exist_glass = False
exist_chopsticks = False
volume = -1
```

2021-07-06 14:32 UTC, mikiya1130 commented on measurevolume/views.py
> +from django import shortcuts
import json削除してくれてありがとうやのに、また余計なん入ってるね。
vscodeの自動補完かも。
まあそのままでも大丈夫です。

2021-07-06 16:02 UTC, mikiya1130 requested changes
> スライスで3行ごと取り出して１の数を数えて平均の半径を求めた。
> np.count_nonzero(img, axis=1)で１行ごとの１の数が配列で得られる。
> どっちがいいかな？

この前複数行ごとに平均取った方が誤差吸収されていいかもとか言ったけど、そんなこと無いかもしれん。
(1行ごとでも3行ごとでも計算結果一緒かも)
処理速度には差あるかもやけど。
ってことで1行ごとか複数行ごとかはどっちでもいいと思うけど、Python標準のループは遅いのでnumpyのメソッドで一気に処理するのが良いかも。
例えば示してくれた`np.count_nonzero(img, axis=1)`使ってこんな感じとか。

```Python
o = np.count_nonzero(img, axis=1)
s = math.pi * (o * mm_pixel / 2) ** 2
v = np.sum(s) * mm_pixel
```

2021-07-06 16:02 UTC, mikiya1130 commented on measurevolume/views.py
> +            r = o / 6
割る6で固定だと、高さが3の倍数でないときに、最後スライスで1or2行だけ取り出されるので正しく計算できません。
あと`r`も`mm_pixel`倍する必要があります。

2021-07-06 16:02 UTC, mikiya1130 commented on measurevolume/views.py
> +            s = img[p : p + 3, 0 : img.shape[1]]
全体を取り出す場合、省略して`s = img[p : p + 3, :]`とも書けます。
(参考までに)

2021-07-06 16:02 UTC, mikiya1130 commented on measurevolume/views.py
> +            s = img[p : p + 3, 0 : img.shape[1]]
**for文を使うパターン**
(while文だとループ変数の初期化、判定、更新処理の記述場所が分散するので)
(好み次第なのでwhile文で全然OKです)

```Python
height = 3
for i in range(0, img.shape[0], height):
    s = img[i: i+height, :]
```

参考：[【Python】シーケンスからn件ずつ取り出したい、n件未満でも取り出したい。 - Qiita](https://qiita.com/Akio-1978/items/c003783517df23d360d0)

2021-07-07 07:57 UTC, mikiya1130 approved these changes
ありがとう
とりあえずマージします

2021-07-07 07:57 UTC, merged